### ISSUE TITLE
Regression: `tmt plan lint` no longer accepts multiple configurations

### ISSUE THREAD

**Issue by stepnem** [psss/tmt#710]
This was broken by commit 918833a33fbe

Steps to reproduce from inside the tmt git root:
```shell
cp examples/multiple/basic.fmf plans/
tmt plan lint
```

Result:
```text
/plans/basic
Traceback (most recent call last):
  [most of Python traceback elided] in _lint_discover
    how = discover.get('how')
AttributeError: 'list' object has no attribute 'get'
```
